// next
import Head from 'next/head'
import React, { useEffect } from 'react';
import { useRouter } from 'next/router';

// styles
import { PageConfig } from '@/styles/PagesConfigElements';

// components
import { Button } from '@mui/material';


export default function Home() {

    const router = useRouter()

    const fetchData = async () => {
        try {
            const response = await fetch('/api/hello');
            const jsonData = await response.json();
            console.log(jsonData);
            
        } catch (error) {
            console.log('Error:', error);
        }
    };

    useEffect(() => {
        fetchData();
    }, []);


    return (
        <>
            <Head>
                <title>VUZF Students</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <PageConfig>
                    <br />
                    <h1>Избери ниво на образование</h1>
                    <Button onClick={() => router.push('bachelors')}>Бакалаври</Button>
                    <br />
                    <br />
                    <br />
                    <Button onClick={() => router.push('masters')}>Магистри</Button>
                </PageConfig>
            </main>
        </>
    )
};