// next
import Head from 'next/head'
import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

// styles
import { PageConfig } from '@/styles/PagesConfigElements';

// components
import { Button } from '@mui/material';
import { auth } from '../../firebase/firebase';






export default function Home() {

    const router = useRouter()


    const fetchData = async () => {
        const currentUser = auth.currentUser;
        if (currentUser) {
            const userToken = await currentUser.getIdToken();

            const response = await fetch('/api/hello', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: userToken,
                },
            });
            if (response.ok) {
                const responseBody = await response.json();
                const message = responseBody.message;
                console.log('Message from backend:', message);
            } else {
                console.error('Error:', response.status);
            }
        }
    };

    fetchData();






    return (
        <>
            <Head>
                <title>VUZF Students</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <PageConfig>
                    <br />
                    <h1>Избери ниво на образование</h1>
                    <Button onClick={() => router.push('bachelors')}>Бакалаври</Button>
                    <br />
                    <br />
                    <br />
                    <Button onClick={() => router.push('masters')}>Магистри</Button>
                </PageConfig>
            </main>
        </>
    )
}