// next
import Head from 'next/head'
import React from 'react';
import { useRouter } from 'next/router';

// styles
import { PageConfig } from '@/styles/PagesConfigElements';

// components
import { Button } from '@mui/material';


// socket io
import { useEffect, useState } from 'react'
import io from 'Socket.IO-client'
let socket: any



export default function Home() {

    // socket.io
    const socketInitializer = async () => {
        await fetch('/api/SocketHandler');
        socket = io();

        socket.on('connect', () => {
            console.log('connected');
        });
    };

    const [input, setInput] = useState('');

    const onChangeHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
        setInput(e.target.value);
        socket.emit('input-change', e.target.value);
    };

    useEffect(() => {
        const initializeSocket = async () => {
            await socketInitializer();
        };

        initializeSocket();
    }, []);
    // socket.io


    const router = useRouter()

    return (
        <>
            <Head>
                <title>VUZF Students</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <PageConfig>
                    <br />
                    <input
                        placeholder="Type something"
                        value={input}
                        onChange={onChangeHandler}
                    />
                    <h1>Избери ниво на образование</h1>
                    <Button onClick={() => router.push('bachelors')}>Бакалаври</Button>
                    <br />
                    <br />
                    <br />
                    <Button onClick={() => router.push('masters')}>Магистри</Button>
                </PageConfig>
            </main>
        </>
    )
}